version: "3.8"

services:
  database:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    container_name: backend
    depends_on:
      - database
    environment:
      DATABASE_URL: "postgresql://postgres:password@database:5432/mydb"
    ports:
      - "8000:8080"

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  db_data:
